version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3307:3306'
    env_file:
      - ./.env
    restart: unless-stopped
  
  backend:
    build: .
    image: captivai
    container_name: captivai
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/src/app  
      - static_volume:/src/app/staticfiles
      - media_volume:/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    restart: unless-stopped
  
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
  
volumes:
  mysql_volume:
  static_volume:
  media_volume: